ncs/Kconfig

The SUIT template directories are now relative to CMAKE_SOURCE_DIR. Modify Kconfig help strings accordingly.

suit: template paths are relative to CMAKE_SOURCE_DIR

---

examples/input_files/envelope_2_hierarchical.yaml
ncs/nordic_top_envelope.yaml.jinja2
ncs/root_with_binary_nordic_top.yaml.jinja2
ncs/root_with_nordic_top_envelope.yaml.jinja2

The class ID check verifies if manifest with given class ID can operate on the installed manifest component, not the class ID of the component.

fix: Class ID checks for INSTLD_MFST components

---

ncs/Kconfig
ncs/app_envelope.yaml.jinja2
ncs/build.py
ncs/nordic_top_envelope.yaml.jinja2
ncs/rad_envelope.yaml.jinja2
ncs/root_with_binary_nordic_top.yaml.jinja2
ncs/root_with_nordic_top_envelope.yaml.jinja2
ncs/secdom_update_envelope.yaml.jinja2
ncs/sysctrl_envelope.yaml.jinja2

* Certain Kconfigs affecting more than one image were moved to sysbuild in sdk-nrf.
* The SUIT build system integration in sdk-nrf now defines a target named `sysbuild` that contains sysbuild Kconfig options. There is no binary or devicetree associated with it.
* All images built within the given sysbuild are now accessible during the template rendering. The image name is the name of the application supplied in `ExternalZephyrProject_Add`, therefore `flash_companion_subimage` was renamed to `flash_companion`.

suit-generator sysbuild adjustments

---

ncs/Kconfig
ncs/rad_envelope.yaml.jinja2
ncs/root_with_binary_nordic_top.yaml.jinja2

Enable local envelope generation only for application and radio cores.
Ref: NCSDK-27372
Signed-off-by: Robert Stypa <robert.stypa@nordicsemi.no>

feat: enable local envelope generation only for rad and app

---

ncs/nordic_top_envelope.yaml.jinja2
ncs/root_with_binary_nordic_top.yaml.jinja2
ncs/root_with_nordic_top_envelope.yaml.jinja2

It is worth checking if all dependency manifests were correctly downloaded prior suit-install sequence execution.
Ref: NCSDK-NONE

ncs: envelopes: Verify child manifests before install

---

ncs/build.py

The file name component of the binary file can now be used in manifest generator.

feat: add binary file name value to template generator

---

suit_generator/suit/authentication.py
suit_generator/suit/envelope.py

Previously, the envelope digest used in the parent envelope was calculated using the same algorithm as the digest for the child envelope authentication block.
Now the digest algorithms used in the parent and child manifests are separate.

fix: calculate envelope digest by specified algorithm

---

ncs/app_envelope.yaml.jinja2
ncs/rad_envelope.yaml.jinja2
ncs/root_with_binary_nordic_top.yaml.jinja2

* templates: remove flash companion from default template
The flash companion is not used in default configurations.
* templates: add retries for streaming operations
Streaming operations, such as calculating the digest or 
suit-directive-copy are now executed at least twice.
This increases the robustness of the update process and may prevent the
device from entering the recovery state when a bit flip occurs during
the streaming operation, but the update candidate is correct and
uncorrupted. In such cases, the bit flip is recoverable.
The device will repeat the streaming operation with the hope that the
bit flip does not occur again.
One source of recoverable bit flips may be interference on the SPI bus when
streaming from external memory, or a bit flip when writing a candidate to NVM.

templates: add streaming operation retry and remove flash companion processing from default template

---

suit_generator/cmd_image.py
tests/test_cmd_image.py

feat: custom vid/cid validation
Add validation for duplicate vid/cid combinations in KConfig file and update corresponding test
Ref: NCSDK-28254
Signed-off-by: Robert Stypa <robert.stypa@nordicsemi.no

Raise exception in case of vid/cid duplicates

---

ncs/build.py

SCFW uses dedicated VERSION file with different schema, so it is necessary to add dedicated handlers for it.
Ref: NCSDK-28945

build.py: Add handlers for SCFW version file

---

ncs/Kconfig

Needed mostly for creation of a separate .zip file, but also allows to simplify the configuration
of a recovery application.
Ref: NCSDK-29206

Added SUIT_RECOVERY Kconfig option

---

suit_generator/args.py
suit_generator/cli.py
suit_generator/cmd_payload_extract.py

The payload allows for extracting/removing/replacing integrated payloads in the envelope.
Ref: NCSDK-29708

Added suit-generator payload_extract command

---

ncs/Kconfig

Changes needed for recovery run from APP_LOCAL_3 manifest

---

suit_generator/suit/manifest.py
suit_generator/suit/types/keys.py

Added parameters for suit_invoke_args

---

suit_generator/cmd_cache_create.py
tests/test_cmd_cache_create.py

This commit extends the suit-generator cache_create command.
It splits it into two commands: from_payloads and from_envelope.
from_payload has the same functionality as the old version of the cache_create command
from_envelope allows extracting payloads directly from the envelope
- also with the possibility to parse the envelope hierarchically and omit certain payloads.

cache_create: Extended the command to extract from envelope

---

ncs/basic_kms.py
ncs/encrypt_script.py
suit_generator/suit_kms_base.py

Removed the usage of nrfkms from the script.
Instead, a dedicated python script containing a SuitKMS class should be used.
Ref: NCSDK-30800

Encryption script using python based libraries

---

examples/input_files/envelope_2_hierarchical.yaml
ncs/nordic_top_envelope.yaml.jinja2
ncs/root_with_nordic_top_envelope.yaml.jinja2

This reverts commit ad6502a937d1e6e11824d3fb546f3d2027c5766a.

Revert "fix: Class ID checks for INSTLD_MFST components"

---

suit_generator/suit/types/common.py

When running in virtual environement on Windows and cbor2 is installed globally with incompatible version compared to one in venv "Deserialisation error" occurs.
Added more informative error message.
Ref: NRFU-1383

fix: deserialisation error due to package conflict error message

---

.github/workflows/contribs.yml

Mark "PR" in red for users without write access.
Ref: NCSDK-31175
Signed-off-by: Robert Stypa <robert.stypa@nordicsemi.no>

feat: add GH action to check contributors write access to the repo

---

ncs/build.py
suit_generator/cmd_image.py
suit_generator/cmd_mpi.py
tests/test_cmd_image.py
tests/test_ncs_sign_script.py

Add --target parameter that allows specifying the
primary image in SUIT configuration. Also improve error message for duplicate image names to be more descriptive.
Ref: NCSDK-30812
Signed-off-by: Robert Stypa <robert.stypa@nordicsemi.no>

feat: Add target parameter to specify primary image

---

ncs/encrypt_script.py
ncs/sign_script.py
suit_generator/cmd_encrypt.py
suit_generator/suit_sign_script_base.py
tests/encrypt_script_mock.py
tests/kms_script_mock.py
tests/sign_script_mock.py
tests/test_cmd_encrypt.py
tests/test_cmd_sign.py
tests/test_ncs_encrypt_script.py
tests/test_ncs_sign_script.py

Extend tests for signing and encryption commands.
